# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tracker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tracker(object):
    def setupUi(self, Tracker):
        Tracker.setObjectName("Tracker")
        Tracker.setEnabled(True)
        Tracker.resize(765, 572)
        self.Label = QtWidgets.QPushButton(Tracker)
        self.Label.setGeometry(QtCore.QRect(0, 0, 151, 61))
        self.Label.setAutoFillBackground(False)
        self.Label.setObjectName("Label")
        self.Train = QtWidgets.QPushButton(Tracker)
        self.Train.setGeometry(QtCore.QRect(0, 60, 151, 61))
        self.Train.setObjectName("Train")
        self.Detect = QtWidgets.QPushButton(Tracker)
        self.Detect.setGeometry(QtCore.QRect(0, 120, 151, 61))
        self.Detect.setObjectName("Detect")
        self.Track = QtWidgets.QPushButton(Tracker)
        self.Track.setGeometry(QtCore.QRect(0, 180, 151, 61))
        self.Track.setObjectName("Track")
        self.textBrowser = QtWidgets.QTextBrowser(Tracker)
        self.textBrowser.setGeometry(QtCore.QRect(150, 0, 611, 571))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Tracker)
        QtCore.QMetaObject.connectSlotsByName(Tracker)

    def retranslateUi(self, Tracker):
        _translate = QtCore.QCoreApplication.translate
        Tracker.setWindowTitle(_translate("Tracker", "Dialog"))
        self.Label.setText(_translate("Tracker", "Label"))
        self.Train.setText(_translate("Tracker", "Train"))
        self.Detect.setText(_translate("Tracker", "Detect"))
        self.Track.setText(_translate("Tracker", "Track"))
